### ISSUE TITLE
Add smoothing to mouse movement

### ISSUE THREAD

**Issue by jamesmugford** [rishikapadia7/AvraLabsEyeControl#6]
It seems like aAvraLabsEyeControl (ALEC :) is currently taking unsmoothed gaze data from the eye tracker. To my knowledge, filtered/smoothed data is available in the EyeX SDK?

Would it be possible to use this smoothed/interpolated data instead to smooth out the motion of the mouse in ALEC? 

Best,
James

**Comment by rishikapadia7** [comment]
I initially tried using the filtered data that comes from the EyeX SDK and turns out it filters/smooths in a way that isn't useful for our mouse replacement. The reason why is that when you have larger eye movements (greater distances across the screen), it would lag behind.

The thresholds that I used for smoothing were tuned perfectly for the mouse replacement and it's various use-cases.
